pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        // Step: Build job
        script {
          // Read job configurations from yaml file, the file name rule is [BUILD_TARGET_JOB_NAME]_[BUILD_MODE]_Config.yaml
          def build_config_file = env.BUILD_TARGET_JOB_NAME + "_" + params.BUILD_MODE + "_" + "Config.yaml"
          def build_config_path = "${env.WORKSPACE}/qa/configs/${build_config_file}"
          def config = readYaml file:build_config_path
          
          // Print all parameters
          echo "BUILD_TARGET_JOB_NAME = ${env.BUILD_TARGET_JOB_NAME}"
          echo "BUILD_MODE = ${params.BUILD_MODE}"
          echo "BUILD_BRANCH_NAME = ${params.BUILD_BRANCH_NAME}"
          echo "build_config_file = ${build_config_file}"
          echo "build_config_path = ${build_config_path}"
          echo "build_server_type = ${config.build_server_type}"
          echo "build_compile_mode = ${config.build_compile_mode}"
          
          // Build job
          def run = build job: env.BUILD_TARGET_JOB_NAME, parameters: [[$class: 'GitParameterValue', name: 'BUILD_BRANCH_NAME', value: params.BUILD_BRANCH_NAME], string(name: 'BUILD_SERVER_TYPE', value: config.build_server_type), string(name: 'BUILD_COMPILE_MODE', value: config.build_compile_mode), booleanParam(name: 'BUILD_FORCE_INCREASE_BUILD_NUMBER', value: false)]

          // Set build description
          currentBuild.description = run.description
        }
      }
    }
  }
}